config/routes.rb
Rails.application.routes.default_url_options[:host] = 'http://localhost:3000'
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  mount RedactorRails::Engine => '/redactor_rails'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root "questions#index"
  post "/widget", controller: :application, action: :widget_data
  get "/search", to: "search#index"

  concern :commentable do
    resources :comments, concerns: :complaints
  end

  concern :rating do
    post :rate
  end

  concern :complaints do
    resources :complaints, only: :create
  end

  resources :categories
  resources :users, except: [:new, :create] do
    post :locale, on: :collection
  end
  resources :questions, concerns: [:commentable, :rating, :complaints] do
    collection do
      post :filter
      get :tag
    end
    post :sign_in_question, on: :member
    resources :answers, concerns: [:commentable, :rating, :complaints] do
      post :helpfull, on: :member
    end
  end

  namespace :admin do
    resources :categories
    resources :complaints, only: [:index, :destroy] do
      delete :parent, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, concerns: [:rating, :commentable, :complaints] do
        get :filter, on: :collection
        resources :answers, concerns: [:rating, :commentable, :complaints] do
          post :helpfull, on: :member
        end
      end
      resources :users do
        member do
          get :questions
          get :answers
          get :comments
          get :statistic
        end
      end
      resources :categories do
        get :questions, on: :member
      end
    end

    namespace :v2 do
      resources :questions
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :complaints, as: :complaintable, dependent: :destroy
  has_many :question_users, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  validates :title, :text, presence: true
  validates :title, uniqueness: true

  acts_as_taggable

  include ModelRate
  include QuestionsHelper

  scope :created_today, -> { where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }
  scope :top, -> { order(rate: :desc) }
  scope :filter, -> (param) { order(param => "desc") }

  def self.signed_users(question)
    question.question_users.each do |signin|
      user = User.find(signin.user_id)
      QuestionMailer.signed_users(user, question).deliver
    end
  end

  def comments_sum
    comments = self.comments.count
    comments += self.answers.map{|c| c.comments.count }.inject{|sum, x| sum += x} unless self.answers.blank?
    comments
  end

  def tag_list
    self.tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      ActsAsTaggableOn::Tag.where(name: n.strip).first_or_create!
    end
  end

  def self.filter_by(filter_param, order_param)
    self.first.touch(:updated_at)
    eval(filter_values[filter_param])
  end

  def humanized_date
    self.created_at.strftime("%H:%M:%S %d.%m.%Y")
  end

  # def answers_count
  #   @answers_count ||= self.answers.size
  # end

  def self.filter_values
    {
        "rate" => "(lambda { |param, order| order(param + ' ' + order) }).call(filter_param, order_param)",
        "new" => "(lambda { |order| order(created_at: order.to_sym).last(10) }).call(order_param)",
        "views" => "(lambda { |param, order| order(param + ' ' + order) }).call(filter_param, order_param)",
        "is_closed" => "(lambda { |param, order| order(param + ' ' + order) }).call(filter_param, order_param)",
        "per_week" => "(lambda { |order| where(created_at: '#{Date.today-1.week} 00:00:00'.to_date..'#{Date.today} 23:59:59'.to_date).order(created_at: order.to_sym) }).call(order_param)",
        "per_month" => "(lambda { |order| where(created_at: '#{Date.today-1.month} 00:00:00'.to_date..'#{Date.today} 23:59:59'.to_date).order(created_at: order.to_sym) }).call(order_param)"
    }
  end
end

app/controllers/api/v1/questions_controller.rb
require 'will_paginate/array'
class Api::V1::QuestionsController < Api::ApiController
  before_action :doorkeeper_authorize!, only: [:create, :update]
  include UserStatistic
  include Rating

  def index
    questions = Question.filter("rate").paginate(page: params[:page] || 1, per_page: 20)
    render json: questions.as_json(only: [:id, :user_id, :title, :views, :rate, :created_at, :answers_count, :comments_count], methods: :category)
  end

  def create
    question = Question.new(question_params)
    if question.save
      PrivatePub.publish_to "/questions", question: question.as_json(methods: [:humanized_date, :answers_count, :comments_sum])
      render json:  response_hash(question), status: :ok
    else
      render json: question.errors.to_json, status: :unprocessable_entity
    end
  end

  def update
    question = Question.find(params[:id])
    if question.update(question_params)
      render json: response_hash(question), status: :ok
    else
      render json: question.errors.to_json, status: :uprocessable_entity
    end
  end

  def filter
    questions = Question.filter(params[:filter]).paginate(page: params[:page] || 1, per_page: 20)
    render json: questions.as_json(except: :tags, methods: [:answers_count, :comments_count, :tag_list])
  end

  def show
    question = Question.includes([:comments, :category, :user, :tags]).find(params[:id])
    render json: response_hash(question)
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    render json: {success: true}.to_json, status: :ok
  end

  private

  def question_params
    params.require(:question).permit(:title, :text, :user_id, :category_id, :tag_list)
  end

  def current_user_voted(question)
    {"current_user_voted" => current_resource_owner.vote_on_question(question) } if current_resource_owner
  end

  def response_hash(question)
    voted = current_user_voted(question)
    question.as_json(methods: [:tag_list, :category, :user]).merge(voted || {})
  end
end

app/controllers/api/v2/questions_controller.rb
module Api
  module V2
    class QuestionsController < Api::ApiController

      def show
        question = Question.includes(:comments, :category, :user, :tags).find(params[:id])
        current_user_voted = {"current_user_voted" => current_resource_owner.vote_on_question(question) } if current_resource_owner
        render json: question.as_json(methods: [:tag_list, :category, :user, :answers, :comments]).merge(current_user_voted || {})
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :filter]
  before_action :define_question, only: [:edit, :show, :update, :destroy, :sign_in_question]
  include Rating
  include UserStatistic

  def index
    @questions = Question.paginate(page: params[:page] || 1, per_page: 20).top
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def show
    @question.update(views: @question.views += 1)
  end

  def create
    question = Question.new(question_params)
    if question.save
      PrivatePub.publish_to "/questions", question: question.as_json(methods: [:humanized_date, :answers_count, :comments_sum])
      render nothing: true
    else
      render json: question.errors.to_json, status: :forbidden
    end
  end

  def update
    if @question.update(question_params)
      Question.delay.signed_users(@question)
      render json: {success: true}, status: :ok
    else
      render json: @question.errors.to_json, status: :forbidden
    end
  end

  def sign_in_question
    if QuestionUser.find_by(user_id: current_user.id, question_id: @question.id)
      render json: {message: "Вы уже подписаны на данное обновление"} and return
    end

    if QuestionUser.create(user_id: current_user.id, question_id: @question.id)
      render json: {message: "Вы подписались на данный вопрос"}, status: :ok
    else
      render json: {error: "К сожалению,подписка не может быть оформлена"}, status: :unprocessible_entity
    end
  end

  def filter
    @questions = Question.filter_by(params[:filter], params[:order]).first(30)
    render partial: "questions/collection", locals: {questions: @questions}, layout: false, status: :ok
  end

  def tag
    @questions =  Question.tagged_with(params[:tag])
    @questions.first.touch(:updated_at) if @questions.first
  end


  def destroy
    @question.destroy
    head :ok
  end

  private

  def define_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :text, :user_id, :category_id, :tag_list)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_for_comment(comment)
    comment.commentable_type.constantize.find(comment.commentable_id).id
  end

  def search_label(classname)
    case classname.to_s
      when "Question"
        "Вопрос"
      when "Answer"
        "Ответ"
      when "Comment"
        "Комментарий"
      when "User"
        "Пользователь"
    end
  end

end

app/views/questions/_collection.html.slim
.questions-list
  - cache "#{collection_key_helper_for :question} - action #{params[:action]} - #{params[:page]}"
    - questions.each do |question|
      = render partial: 'question', locals: {question: question}
    = will_paginate questions, :renderer => BootstrapPagination::Rails unless params[:action].eql?("filter")

app/views/questions/_form.html.slim
= form_for @question, html: {class: "form-horizontal question_form"} do |f|
  = f.hidden_field :user_id, value: current_user.id
  - if params[:action] == "edit"
    = f.hidden_field :action, value: "edit", data: {question: @question.id}
  .form-group
    = f.label t('question.title'), class: 'col-md-2 control-label'
    .col-md-4
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label t('question.text'), class: 'col-md-2 control-label'
    .col-md-5
      = f.text_area :text, class: 'form-control', rows: 10, cols: 10
  .form-group
    = f.label t('question.tags'), class: 'col-md-2 control-label'
    .col-md-5
      = f.text_field :tag_list, class: 'form-control', data: { role: "tagsinput" }
  .form-group
    = f.label t('question.category'), class: 'col-md-2 control-label'
    .col-md-4
      = f.select(:category_id, Category.all.map {|p| [ p.title, p.id ]}, {}, class: 'form-control')
  .col-md-offset-2
    = f.submit t('question.save'), class: 'btn btn-success'
    = link_to t('question.back'), questions_path, class: 'btn btn-default submit-btn'

app/views/questions/_question.html.slim
.question-item
  .main-info
    .question-statistic
      .stat-item
        .data-icon.glyphicon.glyphicon-eye-open
        .data= question.views
      .stat-item
        .data-icon.glyphicon.glyphicon-comment
        .data= question.answers.count
      .stat-item
        .data-icon.glyphicon.glyphicon-list-alt
        .data= question.comments_sum
    .title
      = link_to question.title, question_path(question)
    .timestamp
      = question.created_at.strftime("#{t("question.created_at")} %H:%m, %m.%d.%Y ")
    - if current_user && question.in?(current_user.questions)
      .actions-panel
        = link_to "", edit_question_path(question), class: "glyphicon glyphicon-pencil btn btn-xs btn-success"
        = link_to "", "#", class: "glyphicon glyphicon-remove btn btn-xs btn-danger delete-question", data: {question: question.id, remote: true}
  .category-info
    .category
      = link_to question.category.title, category_path(question.category) if question.category
    .question-tags
      = raw question.tags.map {|t| link_to t, tag_questions_path(tag: t.name), class: "question-tag"}.join(", ")

app/views/questions/edit.html.slim
h1=t("question.edit.title")

= render 'form'

app/views/questions/index.html.slim
- if can? :create, Question
  = link_to t("share.create_question"), new_question_path, class: 'btn btn-info'
.questions-page
  ul.question-filters.nav.nav-tabs
    li.active
      = link_to t("share.filter.rate"), "#", remote: true, class: "glyphicon glyphicon-chevron-down", filter: "rate", order: "desc"
    li
      = link_to t("share.filter.new"), "#", remote: true,filter: "new", order: "desc"
    li
      = link_to t("share.filter.views"), "#", remote: true, filter: "views", order: "desc"
    li
      = link_to t("share.filter.answered"), "#", remote: true, filter: "is_closed", order: "desc"
    li
      = link_to t("share.filter.week"), "#", remote: true, filter: "per_week", order: "desc"
    li
      = link_to t("share.filter.month"), "#", remote: true, filter: "per_month", order: "desc"
  .question-page-content
    = render partial: "collection", locals: {questions: @questions}

= subscribe_to "/questions"

app/views/questions/new.html.slim
h1=t("question.create.title")
= render 'form'

app/views/questions/show.html.slim
- cache key_for_object @question do
  .question-show
    fieldset
      legend
        span.title= @question.title
        span.question-author= " &mdash; #{link_to @question.user.correct_naming, user_path(@question.user)}".html_safe
        span.question-time= @question.created_at.strftime("%H:%M:%I %d.%m.%Y")
      .row
        .col-md-1
          .rate-block data-question="#{@question.id}"
            = link_to "", "#", remote: true, class: "glyphicon glyphicon-chevron-up btn rate-move", data: {rate: "plus"}
            .rate-value
              span= @question.rate
            = link_to "", "#", remote: true, class: "glyphicon glyphicon-chevron-down btn rate-move", data: {rate: "minus"}
        .col-md-8
          .question-category
            .form-group
              label.col-md-2.control-label= t('question.category')
              = raw link_to @question.category.title, category_path(@question.category)
          .question-tags
            .form-group
              label.col-md-2.control-label= t('question.tags')
              = raw @question.tags.map {|t| link_to t, "#", remote: true, class: "question-tag"}.join(", ")
          .question-text
            .form-group
              label
              .col-md-12
                = @question.text.html_safe
    .question-action
      - if current_user && @question.in?(current_user.questions)
        = link_to "", edit_question_path(@question), class: "glyphicon glyphicon-pencil btn btn-success"
      - if current_user.present?
        = link_to t("question.back"), questions_path, class: 'btn btn-default'
        = link_to t("question.answer"), "#", class: 'btn btn-primary add-answer', data: {question: @question.id}, remote: true
        = link_to "", "#", class: "glyphicon glyphicon-comment btn btn-info add-comment", data: {question: @question.id, type: "Question"}, remote: true
        = link_to t('question.subscribe'), "#", remote: true, class: "btn btn-warning sign-in-question", data: {question: @question.id}
        = link_to t('question.complaint'), "#", remote: true, class: "btn btn-danger complain-question", data: {question: @question.id}
    .comments-list
      - cache key_for_nested_resource(@question, @question.comments) do
        - @question.comments.each do |comment|
          = render partial: 'comments/comment', locals: {comment: comment}
    .answers-list data={question: @question.id}
      - cache key_for_nested_resource(@question, @question.answers) do
        - @question.answers.each do |answer|
          = render partial: 'answers/answer', locals: { answer: answer }
    .actions-panel


= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"
= subscribe_to "/questions/#{@question.id}/answers/edit"
= subscribe_to "/questions/#{@question.id}/answers/comments/create"
= subscribe_to "/questions/#{@question.id}/answers/comments/edit"
= subscribe_to "/questions/#{@question.id}/comments/edit"
= subscribe_to "/questions/#{@question.id}/comments/edit"
= subscribe_to "/questions/#{@question.id}/answers/destroy"

app/views/questions/tag.html.slim
= link_to "На список вопросов", questions_path
.tag-search
  h3="Поиск по тегу '#{params[:tag]}':"
  - cache "#{params[:action]}/#{params[:tag]}/#{collection_key_helper_for :question}" do
    = render partial: "collection", locals: {questions: @questions}