config/routes.rb
Rails.application.routes.default_url_options[:host] = 'http://localhost:3000'
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  mount RedactorRails::Engine => '/redactor_rails'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root "questions#index"
  post "/widget", controller: :application, action: :widget_data
  get "/search", to: "search#index"

  concern :commentable do
    resources :comments, concerns: :complaints
  end

  concern :rating do
    post :rate
  end

  concern :complaints do
    resources :complaints, only: :create
  end

  resources :categories
  resources :users, except: [:new, :create] do
    post :locale, on: :collection
  end
  resources :questions, concerns: [:commentable, :rating, :complaints] do
    collection do
      post :filter
      get :tag
    end
    post :sign_in_question, on: :member
    resources :answers, concerns: [:commentable, :rating, :complaints] do
      post :helpfull, on: :member
    end
  end

  namespace :admin do
    resources :categories
    resources :complaints, only: [:index, :destroy] do
      delete :parent, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, concerns: [:rating, :commentable, :complaints] do
        get :filter, on: :collection
        resources :answers, concerns: [:rating, :commentable, :complaints] do
          post :helpfull, on: :member
        end
      end
      resources :users do
        member do
          get :questions
          get :answers
          get :comments
          get :statistic
        end
      end
      resources :categories do
        get :questions, on: :member
      end
    end

    namespace :v2 do
      resources :questions
    end
  end
end

app/views/shared/_search.html.slim
form.navbar-form.navbar-left.search-form role="search"
  .form-group
    = text_field_tag "search", nil, class: "form-control search-text", placeholder: t("share.search.title")
  button type="submit" class="btn btn-primary search-submit"
    = t("share.search.submit")

app/views/shared/_widget.html.slim
.widget
  .title [data-filter="last_create"]
    .glyphicon.glyphicon-chevron-left.left-arrow.arrow data-direction="left"
    .glyphicon.glyphicon-chevron-right.right-arrow.arrow data-direction="right"
    .title-text= "Последние созданные:"

  .content
  - widget.each do |data|
    = render partial: "shared/widget_item", locals: {data: data}

app/views/shared/_widget_item.html.slim
.widget-item
  .id
    = data.id
    .glyphicon.glyphicon-eye-open
  .title
    = link_to data.title, question_path(data)

app/views/shared/flash_messages.html.slim
- if flash[:alert]
  .alert.alert-danger
    button.close[data-dismiss="alert" aria-hidden="true"]="&times;".html_safe
    - flash[:alert].each do |key, value|
      p= key
      ul
        - value.each do |v|
          li= v

- if flash[:success]
  .alert.alert-success
    button.close[data-dismiss="alert" aria-hidden="true"]="&times;".html_safe
    = flash[:success]

- if flash[:notice]
  .alert.alert-info
    button.close[data-dismiss="alert" aria-hidden="true"]="&times;".html_safe
    = flash[:notice]

app/views/shared/login.html.slim
#authorization.tab-pane
  = form_tag "/users/sign_in", class: "form-horizontal" do
    .form-group
      = label_tag "Электронная почта:",nil, for: :email, class: 'control-label col-md-4'
      .col-md-4
        = text_field_tag :email, nil, class: "form-control"
    .form-group
      = label_tag "Пароль:",nil, for: :password, class: 'control-label col-md-4'
      .col-md-4
        = password_field_tag :password, nil, class: "form-control"

app/views/shared/modal_window.html.slim
#myModal.modal.auth-modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"  &times;
        h4#myModalLabel.modal-title StackQ&A
      .modal-body
        ul.nav.nav-tabs
          li= link_to t('share.modal_window.auth'), "#authorization", data: {toggle: "tab"}
          li= link_to t('share.modal_window.reg'), "#registration", data: {toggle: "tab"}
        .tab-content
          = render template: "devise/sessions/new"
          = render template: "devise/registrations/new"
      .modal-footer
        .social
          - User.omniauth_providers.each do |provider|
            = link_to "", omniauth_authorize_path(User, provider), class: provider
        .buttons
          button.btn.btn-default data-dismiss="modal" type="button"
            = t('share.modal_window.close')
          button.btn.btn-success.form-delegate type="button"
            = t('share.modal_window.send')

app/views/shared/registration.html.slim
#registration.tab-pane
  = form_for(User.new, url:registration_path(:user), html: {class: "form-horizontal"}) do
    .form-group
      = label_tag "Электронная почта:", nil, for: :email, class: 'control-label col-md-4'
      .col-md-4
        = email_field_tag :email, nil, class: "form-control"
    .form-group
      = label_tag "Пароль:", nil, for: :password, class: 'control-label col-md-4'
      .col-md-4
        = password_field_tag :password, nil, class: "form-control"
    .form-group
      = label_tag "Повторите пароль:", nil, for: :password_confirmation, class: 'control-label col-md-4'
      .col-md-4
        = password_field_tag :password_confirmation, nil, class: "form-control"
    .form-actions
      = submit_tag "Отправить",  class: 'btn btn-success'