config/routes.rb
Rails.application.routes.default_url_options[:host] = 'http://localhost:3000'
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }

  mount RedactorRails::Engine => '/redactor_rails'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root "questions#index"
  post "/widget", controller: :application, action: :widget_data
  get "/search", to: "search#index"

  concern :commentable do
    resources :comments, concerns: :complaints
  end

  concern :rating do
    post :rate
  end

  concern :complaints do
    resources :complaints, only: :create
  end

  resources :categories
  resources :users, except: [:new, :create] do
    post :locale, on: :collection
  end
  resources :questions, concerns: [:commentable, :rating, :complaints] do
    collection do
      post :filter
      get :tag
    end
    post :sign_in_question, on: :member
    resources :answers, concerns: [:commentable, :rating, :complaints] do
      post :helpfull, on: :member
    end
  end

  namespace :admin do
    resources :categories
    resources :complaints, only: [:index, :destroy] do
      delete :parent, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions, concerns: [:rating, :commentable, :complaints] do
        get :filter, on: :collection
        resources :answers, concerns: [:rating, :commentable, :complaints] do
          post :helpfull, on: :member
        end
      end
      resources :users do
        member do
          get :questions
          get :answers
          get :comments
          get :statistic
        end
      end
      resources :categories do
        get :questions, on: :member
      end
    end

    namespace :v2 do
      resources :questions
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions

  mount_uploader :image, CategoryUploader

  validates :title, :description, presence: true
  validates :title, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    respond_to do |format|
      if category.save
        format.html { redirect_to admin_categories_path }
        format.json { render json: category, status: :ok }
      else
        format.html { render 'new', status: :forbidden }
        format.json { render json: category.errors.to_json, status: :forbidden }
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    respond_to do |format|
      if category.update(category_params)
        format.html { redirect_to admin_categories_path, status: :ok }
        format.json { render json: category, status: :ok }
      else
        format.html { render 'new', status: :forbidden }
        format.json { render json: category.errors.to_json, status: :forbidden }
      end
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    head :ok
  end

  private
  def category_params
    params.require(:category).permit(:title, :description, :image)
  end
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < Api::ApiController
  # before_action :doorkeeper_authorize!

  def index
    categories = Category.paginate(page: params[:page] || 1, per_page: 10)
    render json: categories.as_json, status: :ok
  end

  def questions
    category = Category.find(params[:id])
    render json: category.questions.paginate(page: params[:page] || 1, per_page: 10).as_json(methods: [:tag_list]), status: :ok
  end

  def show
    category = Category.find(params[:id])
    render json: category.as_json, status: :ok
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/views/categories/_category.html.slim
.category_item.row
  .image.col-md-2
    = image_tag category.image.url(:small) || "empty-check-box-th.png"
  .col-md-8
    .row
      .title.category.col-md-4= link_to category.title, category_path(category), class: 'category-title'
      .timestamp.col-md-4= category.created_at
    - if current_user && current_user.is_admin?
      .row.actions
        = link_to t('category.edit'), edit_admin_category_path(category), class: 'btn btn-success'
        = link_to t('category.destroy'), "#", class: 'btn btn-danger delete-category', data: { category: category.id }, remote: true

app/views/categories/index.html.slim
.category-list
  - @categories.each do |category|
    = render partial: "category", locals: {category: category}

app/views/categories/show.html.slim
.category-page.row
  .col-md-10
    .category-title
      h3= @category.title
    .category-main
      .category-desc
        = @category.description.html_safe
      .category-hide
        = link_to t('category.hide'), "#", class: "btn btn-primary glyphicon glyphicon-arrow-up toggle-description", remote: true
  .col-md-2
    .category-image
      = image_tag @category.image.url(:small) || "empty-check-box-th.png"
.categories-questions.row
  - if @category.questions.blank?
    h3 = t('category.empty_questions')
    = link_to "Создать", new_question_path, class: 'btn btn-success'
  - else
    - @category.questions.each do |question|
      = render partial: "questions/question", locals: {question: question}